import "./globals.css";
import { Navigation } from "@/components/navigation";
import {
  ClientSessionProvider,
  ClientTrpcProvider,
} from "@/components/providers";
import { Toaster } from "@repo/ui/toaster";
import { TooltipProvider } from "@repo/ui/tooltip";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <ClientTrpcProvider>
          <ClientSessionProvider>
            <TooltipProvider>
              <Navigation />
              {children}
              <Toaster />
            </TooltipProvider>
          </ClientSessionProvider>
        </ClientTrpcProvider>
      </body>
    </html>
  );
}
